#!/usr/bin/env python

import subprocess
import sys

class BrightnessScale:

    def adjust(self, delta):
        currentBrightness = self.getCurrentBrightness()
        for mon in self.getActiveMonitors():
            self.set_brightness(mon, currentBrightness + delta);

    def getActiveMonitors(self):
        #Find display monitor
        monitor = subprocess.check_output("xrandr -q | grep ' connected' | cut -d ' ' -f1", shell=True)
        return monitor.split('\n')[:-1]

    def getCurrentBrightness(self):
        #Find current brightness
        cmd = "xrandr --verbose | grep -i brightness | cut -f2 -d ' '"
        currB = subprocess.check_output(cmd, shell=True)
        currB = currB.split('\n')[0]
        currB = int(float(currB) * 100)
        return currB

    def set_brightness(self, monitor, brightness):

        target = float(brightness)/100
        if target < 0:
            target = 0

        cmd = "xrandr --output %s --brightness %.2f" % (monitor, target)
        print cmd
        subprocess.call(cmd, shell=True)

if __name__ == "__main__":
    brcontrol = BrightnessScale()
    if len(sys.argv) != 2:
        print("invalid arg")
        sys.exit()

    change = sys.argv[1]
    if change == "inc":
        brcontrol.adjust(10);
    elif change == "dec":
        brcontrol.adjust(-10);
    else:
        print("Invalid arg: '%s'" % (change))
